runtime: python311
entrypoint: gunicorn -b :$PORT finwise_backend.wsgi:application

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  DEBUG: "False"
  DJANGO_SETTINGS_MODULE: "finwise_backend.settings_production"
  ALLOWED_HOSTS: "*"

handlers:
  - url: /static
    static_dir: staticfiles/
    secure: always

  - url: /media
    static_dir: media/
    secure: always

  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup

includes:
  - gae_include.yaml 